#! /bin/bash
#                         ____        __  _____ __         
#                        / __ \____  / /_/ __(_) /__  _____
#                       / / / / __ \/ __/ /_/ / / _ \/ ___/
#                      / /_/ / /_/ / /_/ __/ / /  __(__  ) 
#                     /_____/\____/\__/_/ /_/_/\___/____/  
#                                                          

set -o nounset
set -o errexit

RED='\033[0;31m'
NC='\033[0m'

function install_zsh {
    sudo apt -y install zsh

    chsh -s $(which zsh)
    sudo chsh -s $(which zsh) root

    # Install oh-my-zsh
    sudo apt -y install curl
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

    stow zsh
}

function install_i3 {
    sudo apt -y install i3 xbacklight feh arandr lxappearance compton i3blocks
    stow i3
}

function install_tools {
    stow todo
    sudo apt -y install ranger highlight atool w3m
    sudo apt -y install htop
    sudo apt -y install lnav
    sudo apt -y install vim-gtk
    # Install direnv whenever you need to handle multiple envs

}

function install_tmux {
    sudo apt -y install tmux xclip
    stow tmux
    echo -e "${RED} Edit ~/.zshrc 'plugins=' to add tmux ${NC}"
}

function install_conky {
    sudo apt -y install conky
    stow conky
}

function install_themes {
    stow themes
}

function ask {
    local label=`echo ${1} | sed "s/_/ /g"`
    read -p "${label} (Y/N) ? [Default : $2] : " choice
    choice=${choice:-$2}
    if [[ ${choice} =~ ^[Yy]$ ]]; then
        eval $1
    fi
}

cd $HOME/dotfiles

sudo apt -y install stow

ask install_zsh Y
ask install_tools Y
ask install_i3 N
ask install_tmux N
ask install_conky N
ask install_themes N
