#! /bin/bash
#                         ____        __  _____ __         
#                        / __ \____  / /_/ __(_) /__  _____
#                       / / / / __ \/ __/ /_/ / / _ \/ ___/
#                      / /_/ / /_/ / /_/ __/ / /  __(__  ) 
#                     /_____/\____/\__/_/ /_/_/\___/____/  
#                                                          

cd $HOME/dotfiles

# Install zsh
sudo apt-get -y install zsh

chsh -s $(which zsh)
sudo chsh -s $(which zsh) root

# Install oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

stow zsh

# Install tmux
sudo apt-get -y install tmux
stow tmux

# Install ranger
sudo apt-get -y install ranger
sudo apt-get -y install highlight atool w3m

# Install Dark Grey theme
stow themes

# Install conky
sudo apt-get -y install conky
stow conky

